#!/bin/bash
set -euo pipefail

# Compile on this Mac; upload/monitor on the Pi (board is plugged in there).
# The Pi mounts this repo at PI_REPO via SSHFS, so local build/ is visible remotely.

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
FQBN=arduino:renesas_uno:unor4wifi
PI_HOST=${PI_HOST:-nolan@nolan-pi}
PI_REPO=${PI_REPO:-/home/nolan/src/arduino}
PI_ARDUINO_DIR=$PI_REPO/arduino

NAME=${1:?usage: $0 <SketchName>}
SKETCH=$NAME/$NAME.ino
BUILD_PATH=$SCRIPT_DIR/build/$NAME

# Load MQTT credentials from .envrc (repo root) and generate credentials.h
ENVRC=$SCRIPT_DIR/../.envrc
CREDENTIALS_H=$SCRIPT_DIR/$NAME/credentials.h
if [[ -f "$ENVRC" ]]; then
  # shellcheck source=/dev/null
  source "$ENVRC"
  cat > "$CREDENTIALS_H" <<-CREDEOF
		// Auto-generated by run.sh from .envrc — do not edit, do not commit.
		const char mqtt_user[] = "$MQTT_USER";
		const char mqtt_pass[] = "$MQTT_PASS";
	CREDEOF
  echo "==> generated $CREDENTIALS_H from .envrc" >&2
else
  echo "error: $ENVRC not found — MQTT credentials required" >&2
  exit 1
fi
# Ensure credentials.h is cleaned up on exit
trap 'rm -f "$CREDENTIALS_H"' EXIT

TIMEOUT_BIN=$(command -v timeout || command -v gtimeout || true)
if [[ -z "$TIMEOUT_BIN" ]]; then
  echo "error: need timeout or gtimeout (brew install coreutils)" >&2
  exit 1
fi

run() {
  local label=$1 secs=$2 status
  shift 2
  echo "==> $label (timeout ${secs}s)" >&2
  "$TIMEOUT_BIN" "$secs" "$@" && return 0
  status=$?
  if [[ $status -eq 124 ]]; then
    echo "error: $label timed out after ${secs}s" >&2
  else
    echo "error: $label failed (exit $status)" >&2
  fi
  exit "$status"
}

cd "$SCRIPT_DIR"

# Check that the board is connected on the Pi before compiling
# echo "==> checking for board ($FQBN) on $PI_HOST..." >&2
# PI_BOARD_OUTPUT=$(ssh "$PI_HOST" "bash -l -c 'arduino-cli board list' 2>/dev/null" || true)
# if ! echo "$PI_BOARD_OUTPUT" | grep -q "$FQBN"; then
#   echo "error: board not found ($FQBN) on $PI_HOST. Is it connected?" >&2
#   echo "  Connected boards:" >&2
#   echo "$PI_BOARD_OUTPUT" | sed 's/^/  /' >&2
#   exit 1
# fi

echo "build path $BUILD_PATH"
mkdir -p "$BUILD_PATH"

run "compile (local)" 1000 arduino-cli compile -v --fqbn "$FQBN" --build-path "$BUILD_PATH" "$SKETCH"
sync

echo "==> upload + monitor on $PI_HOST"
# -t: allocate a TTY so serial monitor is interactive
ssh -t "$PI_HOST" "$PI_ARDUINO_DIR/upload-on-pi.sh" "$FQBN" "$NAME"
